version: '3.8'

services:
  nginx:
    container_name: loadbalancer_nginx  
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - fastapi1
      - fastapi2
      - fastapi3
      - fastapi4
      - fastapi5
    networks:
      - app_net

  fastapi1:
    container_name: fastapi_instance_1  
    build: .
    volumes:
      - ./app:/app
    expose:
      - "8000"
    networks:
      - app_net

  fastapi2:
    container_name: fastapi_instance_2  
    build: .
    volumes:
      - ./app:/app
    expose:
      - "8000"
    networks:
      - app_net

  fastapi3:
    container_name: fastapi_instance_3  
    build: .
    volumes:
      - ./app:/app
    expose:
      - "8000"
    networks:
      - app_net

  fastapi4:
    container_name: fastapi_instance_4  
    build: .
    volumes:
      - ./app:/app
    expose:
      - "8000"
    networks:
      - app_net

  fastapi5:
    container_name: fastapi_instance_5  
    build: .
    volumes:
      - ./app:/app
    expose:
      - "8000"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge